package com.troy.test;

import javax.xml.ws.handler.*;

import com.troy.serialization.util.*;

public class Constants {

	public static final String HARRY_POTTER = "Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say\n"
			+ "that they were perfectly normal, thank you very much. They were the last\n"
			+ "people you'd expect to be involved in anything strange or mysterious,\n" + "because they just didn't hold with such nonsense.\n"
			+ "Mr. Dursley was the director of a firm called Grunnings, which made\n"
			+ "drills. He was a big, beefy man with hardly any neck, although he did\n"
			+ "have a very large mustache. Mrs. Dursley was thin and blonde and had\n"
			+ "nearly twice the usual amount of neck, which came in very useful as she\n"
			+ "spent so much of her time craning over garden fences, spying on the\n"
			+ "neighbors. The Dursleys had a small son called Dudley and in their\n" + "opinion there was no finer boy anywhere.\n"
			+ "The Dursleys had everything they wanted, but they also had a secret, and\n"
			+ "their greatest fear was that somebody would discover it. They didn't\n"
			+ "think they could bear it if anyone found out about the Potters. Mrs.\n"
			+ "Potter was Mrs. Dursley's sister, but they hadn't met for several years;\n"
			+ "in fact, Mrs. Dursley pretended she didn't have a sister, because her\n"
			+ "sister and her good-for-nothing husband were as unDursleyish as it was\n"
			+ "possible to be. The Dursleys shuddered to think what the neighbors would\n"
			+ "say if the Potters arrived in the street. The Dursleys knew that the\n"
			+ "Potters had a small son, too, but they had never even seen him. This boy\n"
			+ "was another good reason for keeping the Potters away; they didn't want\n" + "Dudley mixing with a child like that.\n"
			+ "When Mr. and Mrs. Dursley woke up on the dull, gray Tuesday our story\n"
			+ "starts, there was nothing about the cloudy sky outside to suggest that\n"
			+ "strange and mysterious things would soon be happening all over the\n"
			+ "country. Mr. Dursley hummed as he picked out his most boring tie for\n"
			+ "work, and Mrs. Dursley gossiped away happily as she wrestled a screaming\n" + "Dudley into his high chair.\n"
			+ "None of them noticed a large, tawny owl flutter past the window.\n"
			+ "At half past eight, Mr. Dursley picked up his briefcase, pecked Mrs.\n"
			+ "Dursley on the cheek, and tried to kiss Dudley good-bye but missed,\n" + "\n"
			+ "because Dudley was now having a tantrum and throwing his cereal at the\n"
			+ "walls. \"Little tyke,\" chortled Mr. Dursley as he left the house. He got\n" + "into his car and backed out of number four's drive.\n"
			+ "It was on the corner of the street that he noticed the first sign of\n"
			+ "something peculiar -- a cat reading a map. For a second, Mr. Dursley\n"
			+ "didn't realize what he had seen -- then he jerked his head around to\n"
			+ "look again. There was a tabby cat standing on the corner of Privet\n"
			+ "Drive, but there wasn't a map in sight. What could he have been thinking\n"
			+ "of? It must have been a trick of the light. Mr. Dursley blinked and\n"
			+ "stared at the cat. It stared back. As Mr. Dursley drove around the\n"
			+ "corner and up the road, he watched the cat in his mirror. It was now\n"
			+ "reading the sign that said Privet Drive -- no, looking at the sign; cats\n"
			+ "couldn't read maps or signs. Mr. Dursley gave himself a little shake and\n"
			+ "put the cat out of his mind. As he drove toward town he thought of\n"
			+ "nothing except a large order of drills he was hoping to get that day.\n"
			+ "But on the edge of town, drills were driven out of his mind by something\n"
			+ "else. As he sat in the usual morning traffic jam, he couldn't help\n"
			+ "noticing that there seemed to be a lot of strangely dressed people\n"
			+ "about. People in cloaks. Mr. Dursley couldn't bear people who dressed in\n"
			+ "funny clothes -- the getups you saw on young people! He supposed this\n"
			+ "was some stupid new fashion. He drummed his fingers on the steering\n"
			+ "wheel and his eyes fell on a huddle of these weirdos standing quite\n"
			+ "close by. They were whispering excitedly together. Mr. Dursley was\n"
			+ "enraged to see that a couple of them weren't young at all; why, that man\n"
			+ "had to be older than he was, and wearing an emerald-green cloak! The\n"
			+ "nerve of him! But then it struck Mr. Dursley that this was probably some\n"
			+ "silly stunt -- these people were obviously collecting for something...\n"
			+ "yes, that would be it. The traffic moved on and a few minutes later, Mr.\n"
			+ "Dursley arrived in the Grunnings parking lot, his mind back on drills.\n"
			+ "Mr. Dursley always sat with his back to the window in his office on the\n"
			+ "ninth floor. If he hadn't, he might have found it harder to concentrate\n"
			+ "on drills that morning. He didn't see the owls swoop ing past in broad\n"
			+ "daylight, though people down in the street did; they pointed and gazed\n"
			+ "open- mouthed as owl after owl sped overhead. Most of them had never\n"
			+ "seen an owl even at nighttime. Mr. Dursley, however, had a perfectly\n"
			+ "normal, owl-free morning. He yelled at five different people. He made\n"
			+ "several important telephone calls and shouted a bit more. He was in a\n"
			+ "very good mood until lunchtime, when he thought he'd stretch his legs\n"
			+ "and walk across the road to buy himself a bun from the bakery.\n" + "\n"
			+ "He'd forgotten all about the people in cloaks until he passed a group of\n"
			+ "them next to the baker's. He eyed them angrily as he passed. He didn't\n"
			+ "know why, but they made him uneasy. This bunch were whispering\n"
			+ "excitedly, too, and he couldn't see a single collecting tin. It was on\n"
			+ "his way back past them, clutching a large doughnut in a bag, that he\n" + "caught a few words of what they were saying.\n"
			+ "\"The Potters, that's right, that's what I heard yes, their son, Harry\"\n"
			+ "Mr. Dursley stopped dead. Fear flooded him. He looked back at the\n"
			+ "whisperers as if he wanted to say something to them, but thought better\n" + "of it.\n"
			+ "He dashed back across the road, hurried up to his office, snapped at his\n"
			+ "secretary not to disturb him, seized his telephone, and had almost\n"
			+ "finished dialing his home number when he changed his mind. He put the\n"
			+ "receiver back down and stroked his mustache, thinking... no, he was\n"
			+ "being stupid. Potter wasn't such an unusual name. He was sure there were\n"
			+ "lots of people called Potter who had a son called Harry. Come to think\n"
			+ "of it, he wasn't even sure his nephew was called Harry. He'd never even\n"
			+ "seen the boy. It might have been Harvey. Or Harold. There was no point\n"
			+ "in worrying Mrs. Dursley; she always got so upset at any mention of her\n"
			+ "sister. He didn't blame her -- if he'd had a sister like that... but all\n" + "the same, those people in cloaks...\n"
			+ "He found it a lot harder to concentrate on drills that afternoon and\n"
			+ "when he left the building at five o'clock, he was still so worried that\n" + "he walked straight into someone just outside the door.\n"
			+ "\"Sorry,\" he grunted, as the tiny old man stumbled and almost fell. It\n"
			+ "was a few seconds before Mr. Dursley realized that the man was wearing a\n"
			+ "violet cloak. He didn't seem at all upset at being almost knocked to the\n"
			+ "ground. On the contrary, his face split into a wide smile and he said in\n"
			+ "a squeaky voice that made passersby stare, \"Don't be sorry, my dear sir,\n"
			+ "for nothing could upset me today! Rejoice, for You-Know-Who has gone at\n"
			+ "last! Even Muggles like yourself should be celebrating, this happy,\n" + "happy day!\"\n"
			+ "And the old man hugged Mr. Dursley around the middle and walked off.\n"
			+ "Mr. Dursley stood rooted to the spot. He had been hugged by a complete\n"
			+ "stranger. He also thought he had been called a Muggle, whatever that\n"
			+ "was. He was rattled. He hurried to his car and set off for home, hoping\n" + "\n"
			+ "he was imagining things, which he had never hoped before, because he\n" + "didn't approve of imagination.\n"
			+ "As he pulled into the driveway of number four, the first thing he saw --\n"
			+ "and it didn't improve his mood -- was the tabby cat he'd spotted that\n"
			+ "morning. It was now sitting on his garden wall. He was sure it was the\n" + "same one; it had the same markings around its eyes.\n"
			+ "\"Shoo!\" said Mr. Dursley loudly. The cat didn't move. It just gave him a\n"
			+ "stern look. Was this normal cat behavior? Mr. Dursley wondered. Trying\n"
			+ "to pull himself together, he let himself into the house. He was still\n" + "determined not to mention anything to his wife.\n"
			+ "Mrs. Dursley had had a nice, normal day. She told him over dinner all\n"
			+ "about Mrs. Next Door's problems with her daughter and how Dudley had\n"
			+ "learned a new word \"Won't!\". Mr. Dursley tried to act normally. When\n"
			+ "Dudley had been put to bed, he went into the living room in time to\n" + "catch the last report on the evening news:\n"
			+ "\"And finally, bird-watchers everywhere have reported that the nation's\n"
			+ "owls have been behaving very unusually today. Although owls normally\n"
			+ "hunt at night and are hardly ever seen in daylight, there have been\n"
			+ "hundreds of sightings of these birds flying in every direction since\n"
			+ "sunrise. Experts are unable to explain why the owls have suddenly\n"
			+ "changed their sleeping pattern.\" The newscaster allowed himself a grin.\n"
			+ "\"Most mysterious. And now, over to Jim McGuffin with the weather. Going\n" + "to be any more showers of owls tonight, Jim?\"\n"
			+ "\"Well, Ted,\" said the weatherman, \"I don't know about that, but it's not\n"
			+ "only the owls that have been acting oddly today. Viewers as far apart as\n"
			+ "Kent, Yorkshire, and Dundee have been phoning in to tell me that instead\n"
			+ "of the rain I promised yesterday, they've had a downpour of shooting\n"
			+ "stars! Perhaps people have been celebrating Bonfire Night early -- it's\n"
			+ "not until next week, folks! But I can promise a wet night tonight.\"\n"
			+ "Mr. Dursley sat frozen in his armchair. Shooting stars all over Britain?\n"
			+ "Owls flying by daylight? Mysterious people in cloaks all over the place?\n" + "And a whisper, a whisper about the Potters...\n"
			+ "Mrs. Dursley came into the living room carrying two cups of tea. It was\n"
			+ "no good. He'd have to say something to her. He cleared his throat\n"
			+ "nervously. \"Er -- Petunia, dear -- you haven't heard from your sister\n" + "lately, have you?\"\n" + "\n"
			+ "As he had expected, Mrs. Dursley looked shocked and angry. After all,\n" + "they normally pretended she didn't have a sister.\n"
			+ "\"No,\" she said sharply. \"Why?\"\n" + "\"Funny stuff on the news,\" Mr. Dursley mumbled. \"Owls... shooting\n"
			+ "stars... and there were a lot of funny-looking people in town today...\"\n" + "\"So?\" snapped Mrs. Dursley.\n"
			+ "\"Well, I just thought... maybe... it was something to do with... you\n" + "know... her crowd.\"\n"
			+ "Mrs. Dursley sipped her tea through pursed lips. Mr. Dursley wondered\n"
			+ "whether he dared tell her he'd heard the name \"Potter.\" He decided he\n"
			+ "didn't dare. Instead he said, as casually as he could, \"Their son --\n" + "he'd be about Dudley's age now, wouldn't he?\"\n"
			+ "\"I suppose so,\" said Mrs. Dursley stiffly.\n" + "\"What's his name again? Howard, isn't it?\"\n"
			+ "\"Harry. Nasty, common name, if you ask me.\"\n" + "\"Oh, yes,\" said Mr. Dursley, his heart sinking horribly. \"Yes, I quite\n"
			+ "agree.\"\n" + "He didn't say another word on the subject as they went upstairs to bed.\n"
			+ "While Mrs. Dursley was in the bathroom, Mr. Dursley crept to the bedroom\n"
			+ "window and peered down into the front garden. The cat was still there.\n"
			+ "It was staring down Privet Drive as though it were waiting for\n" + "something.\n"
			+ "Was he imagining things? Could all this have anything to do with the\n"
			+ "Potters? If it did... if it got out that they were related to a pair of\n" + "-- well, he didn't think he could bear it.\n"
			+ "The Dursleys got into bed. Mrs. Dursley fell asleep quickly but Mr.\n"
			+ "Dursley lay awake, turning it all over in his mind. His last, comforting\n"
			+ "thought before he fell asleep was that even if the Potters were\n"
			+ "involved, there was no reason for them to come near him and Mrs.\n"
			+ "Dursley. The Potters knew very well what he and Petunia thought about\n" + "\n"
			+ "them and their kind.... He couldn't see how he and Petunia could get\n"
			+ "mixed up in anything that might be going on -- he yawned and turned over\n" + "-- it couldn't affect them....\n"
			+ "How very wrong he was.\n" + "Mr. Dursley might have been drifting into an uneasy sleep, but the cat\n"
			+ "on the wall outside was showing no sign of sleepiness. It was sitting as\n"
			+ "still as a statue, its eyes fixed unblinkingly on the far corner of\n"
			+ "Privet Drive. It didn't so much as quiver when a car door slammed on the\n"
			+ "next street, nor when two owls swooped overhead. In fact, it was nearly\n" + "midnight before the cat moved at all.\n"
			+ "A man appeared on the corner the cat had been watching, appeared so\n"
			+ "suddenly and silently you'd have thought he'd just popped out of the\n" + "ground. The cat's tail twitched and its eyes narrowed.\n"
			+ "Nothing like this man had ever been seen on Privet Drive. He was tall,\n"
			+ "thin, and very old, judging by the silver of his hair and beard, which\n"
			+ "were both long enough to tuck into his belt. He was wearing long robes,\n"
			+ "a purple cloak that swept the ground, and high-heeled, buckled boots.\n"
			+ "His blue eyes were light, bright, and sparkling behind half-moon\n"
			+ "spectacles and his nose was very long and crooked, as though it had been\n"
			+ "broken at least twice. This man's name was Albus Dumbledore.\n"
			+ "Albus Dumbledore didn't seem to realize that he had just arrived in a\n"
			+ "street where everything from his name to his boots was unwelcome. He was\n"
			+ "busy rummaging in his cloak, looking for something. But he did seem to\n"
			+ "realize he was being watched, because he looked up suddenly at the cat,\n"
			+ "which was still staring at him from the other end of the street. For\n"
			+ "some reason, the sight of the cat seemed to amuse him. He chuckled and\n" + "muttered, \"I should have known.\"\n"
			+ "He found what he was looking for in his inside pocket. It seemed to be a\n"
			+ "silver cigarette lighter. He flicked it open, held it up in the air, and\n"
			+ "clicked it. The nearest street lamp went out with a little pop. He\n"
			+ "clicked it again -- the next lamp flickered into darkness. Twelve times\n"
			+ "he clicked the Put-Outer, until the only lights left on the whole street\n"
			+ "were two tiny pinpricks in the distance, which were the eyes of the cat\n"
			+ "watching him. If anyone looked out of their window now, even beady-eyed\n"
			+ "Mrs. Dursley, they wouldn't be able to see anything that was happening\n"
			+ "down on the pavement. Dumbledore slipped the Put-Outer back inside his\n"
			+ "cloak and set off down the street toward number four, where he sat down\n" + "\n"
			+ "on the wall next to the cat. He didn't look at it, but after a moment he\n" + "spoke to it.\n"
			+ "\"Fancy seeing you here, Professor McGonagall.\"\n" + "He turned to smile at the tabby, but it had gone. Instead he was smiling\n"
			+ "at a rather severe-looking woman who was wearing square glasses exactly\n"
			+ "the shape of the markings the cat had had around its eyes. She, too, was\n"
			+ "wearing a cloak, an emerald one. Her black hair was drawn into a tight\n" + "bun. She looked distinctly ruffled.\n"
			+ "\"How did you know it was me?\" she asked.\n" + "\"My dear Professor, I 've never seen a cat sit so stiffly.\"\n"
			+ "\"You'd be stiff if you'd been sitting on a brick wall all day,\" said\n" + "Professor McGonagall.\n"
			+ "\"All day? When you could have been celebrating? I must have passed a\n" + "dozen feasts and parties on my way here.\"\n"
			+ "Professor McGonagall sniffed angrily.\n" + "\"Oh yes, everyone's celebrating, all right,\" she said impatiently.\n"
			+ "\"You'd think they'd be a bit more careful, but no -- even the Muggles\n"
			+ "have noticed something's going on. It was on their news.\" She jerked her\n"
			+ "head back at the Dursleys' dark living-room window. \"I heard it. Flocks\n"
			+ "of owls... shooting stars.... Well, they're not completely stupid. They\n"
			+ "were bound to notice something. Shooting stars down in Kent -- I'll bet\n" + "that was Dedalus Diggle. He never had much sense.\"\n"
			+ "\"You can't blame them,\" said Dumbledore gently. \"We've had precious\n" + "little to celebrate for eleven years.\"\n"
			+ "\"I know that,\" said Professor McGonagall irritably. \"But that's no\n"
			+ "reason to lose our heads. People are being downright careless, out on\n"
			+ "the streets in broad daylight, not even dressed in Muggle clothes,\n" + "swapping rumors.\"\n"
			+ "She threw a sharp, sideways glance at Dumbledore here, as though hoping\n"
			+ "he was going to tell her something, but he didn't, so she went on. \"A\n"
			+ "fine thing it would be if, on the very day YouKnow-Who seems to have\n"
			+ "disappeared at last, the Muggles found out about us all. I suppose he\n" + "\n" + "really has gone, Dumbledore?\"\n"
			+ "\"It certainly seems so,\" said Dumbledore. \"We have much to be thankful\n" + "for. Would you care for a lemon drop?\"\n"
			+ "\"A what?\"\n" + "\"A lemon drop. They're a kind of Muggle sweet I'm rather fond of\"\n"
			+ "\"No, thank you,\" said Professor McGonagall coldly, as though she didn't\n"
			+ "think this was the moment for lemon drops. \"As I say, even if\n" + "You-Know-Who has gone -\"\n"
			+ "\"My dear Professor, surely a sensible person like yourself can call him\n"
			+ "by his name? All this 'You- Know-Who' nonsense -- for eleven years I\n"
			+ "have been trying to persuade people to call him by his proper name:\n"
			+ "Voldemort.\" Professor McGonagall flinched, but Dumbledore, who was\n"
			+ "unsticking two lemon drops, seemed not to notice. \"It all gets so\n"
			+ "confusing if we keep saying 'You-Know-Who.' I have never seen any reason\n" + "to be frightened of saying Voldemort's name.\n"
			+ "\"I know you haven 't, said Professor McGonagall, sounding half\n"
			+ "exasperated, half admiring. \"But you're different. Everyone knows you're\n"
			+ "the only one You-Know- oh, all right, Voldemort, was frightened of.\"\n"
			+ "\"You flatter me,\" said Dumbledore calmly. \"Voldemort had powers I will\n" + "never have.\"\n"
			+ "\"Only because you're too -- well -- noble to use them.\"\n"
			+ "\"It's lucky it's dark. I haven't blushed so much since Madam Pomfrey\n" + "told me she liked my new earmuffs.\"\n"
			+ "Professor McGonagall shot a sharp look at Dumbledore and said, \"The owls\n"
			+ "are nothing next to the rumors that are flying around. You know what\n"
			+ "everyone's saying? About why he's disappeared? About what finally\n" + "stopped him?\"\n"
			+ "It seemed that Professor McGonagall had reached the point she was most\n"
			+ "anxious to discuss, the real reason she had been waiting on a cold, hard\n"
			+ "wall all day, for neither as a cat nor as a woman had she fixed\n"
			+ "Dumbledore with such a piercing stare as she did now. It was plain that\n"
			+ "whatever \"everyone\" was saying, she was not going to believe it until\n" + "\n"
			+ "Dumbledore told her it was true. Dumbledore, however, was choosing\n" + "another lemon drop and did not answer.\n"
			+ "\"What they're saying,\" she pressed on, \"is that last night Voldemort\n"
			+ "turned up in Godric's Hollow. He went to find the Potters. The rumor is\n"
			+ "that Lily and James Potter are -- are -- that they're -- dead. \"\n" + "Dumbledore bowed his head. Professor McGonagall gasped.\n"
			+ "\"Lily and James... I can't believe it... I didn't want to believe it...\n" + "Oh, Albus...\"\n"
			+ "Dumbledore reached out and patted her on the shoulder. \"I know... I\n" + "know...\" he said heavily.\n"
			+ "Professor McGonagall's voice trembled as she went on. \"That's not all.\n"
			+ "They're saying he tried to kill the Potter's son, Harry. But -- he\n"
			+ "couldn't. He couldn't kill that little boy. No one knows why, or how,\n"
			+ "but they're saying that when he couldn't kill Harry Potter, Voldemort's\n" + "power somehow broke -- and that's why he's gone.\n"
			+ "Dumbledore nodded glumly.\n" + "\"It's -- it's true?\" faltered Professor McGonagall. \"After all he's\n"
			+ "done... all the people he's killed... he couldn't kill a little boy?\n"
			+ "It's just astounding... of all the things to stop him... but how in the\n" + "name of heaven did Harry survive?\"\n"
			+ "\"We can only guess,\" said Dumbledore. \"We may never know.\"\n"
			+ "Professor McGonagall pulled out a lace handkerchief and dabbed at her\n"
			+ "eyes beneath her spectacles. Dumbledore gave a great sniff as he took a\n"
			+ "golden watch from his pocket and examined it. It was a very odd watch.\n"
			+ "It had twelve hands but no numbers; instead, little planets were moving\n"
			+ "around the edge. It must have made sense to Dumbledore, though, because\n"
			+ "he put it back in his pocket and said, \"Hagrid's late. I suppose it was\n" + "he who told you I'd be here, by the way?\"\n"
			+ "\"Yes,\" said Professor McGonagall. \"And I don't suppose you're going to\n" + "tell me why you're here, of all places?\"\n"
			+ "\"I've come to bring Harry to his aunt and uncle. They're the only family\n" + "he has left now.\"\n" + "\n"
			+ "\"You don't mean -- you can't mean the people who live here?\" cried\n"
			+ "Professor McGonagall, jumping to her feet and pointing at number four.\n"
			+ "\"Dumbledore -- you can't. I've been watching them all day. You couldn't\n"
			+ "find two people who are less like us. And they've got this son -- I saw\n"
			+ "him kicking his mother all the way up the street, screaming for sweets.\n" + "Harry Potter come and live here!\"\n"
			+ "\"It's the best place for him,\" said Dumbledore firmly. \"His aunt and\n"
			+ "uncle will be able to explain everything to him when he's older. I've\n" + "written them a letter.\"\n"
			+ "\"A letter?\" repeated Professor McGonagall faintly, sitting back down on\n"
			+ "the wall. \"Really, Dumbledore, you think you can explain all this in a\n"
			+ "letter? These people will never understand him! He'll be famous -- a\n"
			+ "legend -- I wouldn't be surprised if today was known as Harry Potter day\n"
			+ "in the future -- there will be books written about Harry -- every child\n" + "in our world will know his name!\"\n"
			+ "\"Exactly,\" said Dumbledore, looking very seriously over the top of his\n"
			+ "half-moon glasses. \"It would be enough to turn any boy's head. Famous\n"
			+ "before he can walk and talk! Famous for something he won't even\n"
			+ "remember! CarA you see how much better off he'll be, growing up away\n" + "from all that until he's ready to take it?\"\n"
			+ "Professor McGonagall opened her mouth, changed her mind, swallowed, and\n"
			+ "then said, \"Yes -- yes, you're right, of course. But how is the boy\n"
			+ "getting here, Dumbledore?\" She eyed his cloak suddenly as though she\n" + "thought he might be hiding Harry underneath it.\n"
			+ "\"Hagrid's bringing him.\"\n" + "\"You think it -- wise -- to trust Hagrid with something as important as\n" + "this?\"\n"
			+ "I would trust Hagrid with my life,\" said Dumbledore.\n" + "\"I'm not saying his heart isn't in the right place,\" said Professor\n"
			+ "McGonagall grudgingly, \"but you can't pretend he's not careless. He does\n" + "tend to -- what was that?\"\n"
			+ "A low rumbling sound had broken the silence around them. It grew\n"
			+ "steadily louder as they looked up and down the street for some sign of a\n" + "\n"
			+ "headlight; it swelled to a roar as they both looked up at the sky -- and\n"
			+ "a huge motorcycle fell out of the air and landed on the road in front of\n" + "them.\n"
			+ "If the motorcycle was huge, it was nothing to the man sitting astride\n"
			+ "it. He was almost twice as tall as a normal man and at least five times\n"
			+ "as wide. He looked simply too big to be allowed, and so wild - long\n"
			+ "tangles of bushy black hair and beard hid most of his face, he had hands\n"
			+ "the size of trash can lids, and his feet in their leather boots were\n"
			+ "like baby dolphins. In his vast, muscular arms he was holding a bundle\n" + "of blankets.\n"
			+ "\"Hagrid,\" said Dumbledore, sounding relieved. \"At last. And where did\n" + "you get that motorcycle?\"\n"
			+ "\"Borrowed it, Professor Dumbledore, sit,\" said the giant, climbing\n"
			+ "carefully off the motorcycle as he spoke. \"Young Sirius Black lent it to\n" + "me. I've got him, sir.\"\n"
			+ "\"No problems, were there?\"\n" + "\"No, sir -- house was almost destroyed, but I got him out all right\n"
			+ "before the Muggles started swarmin' around. He fell asleep as we was\n" + "flyin' over Bristol.\"\n"
			+ "Dumbledore and Professor McGonagall bent forward over the bundle of\n"
			+ "blankets. Inside, just visible, was a baby boy, fast asleep. Under a\n"
			+ "tuft of jet-black hair over his forehead they could see a curiously\n" + "shaped cut, like a bolt of lightning.\n"
			+ "\"Is that where -?\" whispered Professor McGonagall.\n" + "\"Yes,\" said Dumbledore. \"He'll have that scar forever.\"\n"
			+ "\"Couldn't you do something about it, Dumbledore?\"\n" + "\"Even if I could, I wouldn't. Scars can come in handy. I have one myself\n"
			+ "above my left knee that is a perfect map of the London Underground. Well\n"
			+ "-- give him here, Hagrid -- we'd better get this over with.\"\n"
			+ "Dumbledore took Harry in his arms and turned toward the Dursleys' house.\n"
			+ "\"Could I -- could I say good-bye to him, sir?\" asked Hagrid. He bent his\n" + "\n"
			+ "great, shaggy head over Harry and gave him what must have been a very\n"
			+ "scratchy, whiskery kiss. Then, suddenly, Hagrid let out a howl like a\n" + "wounded dog.\n"
			+ "\"Shhh!\" hissed Professor McGonagall, \"you'll wake the Muggles!\"\n"
			+ "\"S-s-sorry,\" sobbed Hagrid, taking out a large, spotted handkerchief and\n"
			+ "burying his face in it. \"But I c-c-can't stand it -- Lily an' James dead\n"
			+ "-- an' poor little Harry off ter live with Muggles -\"\n" + "\"Yes, yes, it's all very sad, but get a grip on yourself, Hagrid, or\n"
			+ "we'll be found,\" Professor McGonagall whispered, patting Hagrid gingerly\n"
			+ "on the arm as Dumbledore stepped over the low garden wall and walked to\n"
			+ "the front door. He laid Harry gently on the doorstep, took a letter out\n"
			+ "of his cloak, tucked it inside Harry's blankets, and then came back to\n"
			+ "the other two. For a full minute the three of them stood and looked at\n"
			+ "the little bundle; Hagrid's shoulders shook, Professor McGonagall\n"
			+ "blinked furiously, and the twinkling light that usually shone from\n" + "Dumbledore's eyes seemed to have gone out.\n"
			+ "\"Well,\" said Dumbledore finally, \"that's that. We've no business staying\n"
			+ "here. We may as well go and join the celebrations.\"\n"
			+ "\"Yeah,\" said Hagrid in a very muffled voice, \"I'll be takin' Sirius his\n"
			+ "bike back. G'night, Professor McGonagall -- Professor Dumbledore, sir.\"\n"
			+ "Wiping his streaming eyes on his jacket sleeve, Hagrid swung himself\n"
			+ "onto the motorcycle and kicked the engine into life; with a roar it rose\n" + "into the air and off into the night.\n"
			+ "\"I shall see you soon, I expect, Professor McGonagall,\" said Dumbledore,\n"
			+ "nodding to her. Professor McGonagall blew her nose in reply.\n"
			+ "Dumbledore turned and walked back down the street. On the corner he\n"
			+ "stopped and took out the silver Put-Outer. He clicked it once, and\n"
			+ "twelve balls of light sped back to their street lamps so that Privet\n"
			+ "Drive glowed suddenly orange and he could make out a tabby cat slinking\n"
			+ "around the corner at the other end of the street. He could just see the\n" + "bundle of blankets on the step of number four.\n"
			+ "\"Good luck, Harry,\" he murmured. He turned on his heel and with a swish\n" + "of his cloak, he was gone.\n" + "\n"
			+ "A breeze ruffled the neat hedges of Privet Drive, which lay silent and\n"
			+ "tidy under the inky sky, the very last place you would expect\n"
			+ "astonishing things to happen. Harry Potter rolled over inside his\n"
			+ "blankets without waking up. One small hand closed on the letter beside\n"
			+ "him and he slept on, not knowing he was special, not knowing he was\n"
			+ "famous, not knowing he would be woken in a few hours' time by Mrs.\n"
			+ "Dursley's scream as she opened the front door to put out the milk\n"
			+ "bottles, nor that he would spend the next few weeks being prodded and\n"
			+ "pinched by his cousin Dudley... He couldn't know that at this very\n"
			+ "moment, people meeting in secret all over the country were holding up\n"
			+ "their glasses and saying in hushed voices: \"To Harry Potter -- the boy\n" + "who lived!\"";
	
	public static final String BIG_HARRY_POTTER = getBig(HARRY_POTTER, 100_000_000);

	public static final String VLE8_TEST = "123456789 VLE8" + '\u1940';

	private static String getBig(String base, int size) {
		int count = 0;
		char[] chars = new char[size];
		char[] baseChars = MiscUtil.getCharsFast(base);
		while (count < size) {
			int toWrite = Math.min(baseChars.length, size - count);
			System.arraycopy(baseChars, 0, chars, count, toWrite);
			count += toWrite;
		}
		return MiscUtil.createString(chars);
	}
}
